import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./component/navbar";
import { OpenProvider } from "./hooks/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="antialiased selection:bg-[#F2f2f2] selection:text-gray-950">
        <Navbar />
        <OpenProvider>{children}</OpenProvider>
      </body>
    </html>
  );
}
